### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [eriplume/sales_buddy#108]
MVPリリースレビューお疲れ様でした！
とても完成度が高くてあまり指摘する点がないのでよかった点を中心にフィードバックさせていただければと思います
本リリースの予定日をこのissueのコメントに返答していただけますとありがたいです 🙇 

## サンプルページ
ログインしなくても一通りの機能を閲覧できるのが実際に使い始める前にサービスイメージを掴みやすくてとても良いと思いました。

## 使い方のヘルプ
目につきやすいところにヘルプを表示するボタンがあり、迷わずに使えました

## レスポンシブ
スマホでも使いやすいように工夫されていて良いと思いました

## ヘッダー
PC画面はダッシュボードへの導線がハンバーガーメニューで隠れているのでヘッダーのロゴのところにダッシュボードへのリンクを設定しても良いかもです

**Comment by eriplume** [comment]
@kenchasonakai 

レビューありがとうございます！
2/12に本リリースしたいと思います。

ご確認よろしくお願いいたします。
