### ISSUE TITLE
チーム機能の中身の検討

### ISSUE THREAD

**Issue by eriplume** [eriplume/sales_buddy#113]
## チャット機能（チーム機能内）について

卒業試験のアプリ設計の段階で、
>READMEに書かれている以外で現在考えている案（追加サービス・追加機能）をREADMEに記載してください。（拡張性の確認）

上記に対して、チーム機能として以下の案を上げておりました。
①チームタスク管理機能
②チャット機能

しかし当アプリのテーマや解決したい問題を考えると②チャット機能は不要な気がしています...
ユーザー同士でリアルタイムチャットをする目的がないし、当アプリの使用シーンにも紐付かないなと。

現状、チーム機能として
- チームの作成（招待）/ チームへの参加
- 所属チームでのタスク管理
チームタスク/ 個人タスクを登録できる。店舗でやらなければならない業務、個人の担当業務やタスクを共有することで店舗の円滑なタイムマネジメントや業務漏れを防ぐといった目的

こちらを実装し終わっております。

②の代替案として、チームタスク機能を拡張させて、例えばタスクが登録された際にLINE通知を飛ばす、タスクに関してコメントができるなどすれば、上記にあげた目的をより実現しやすいのかなと考えていますがいかがでしょうか。

また、その他本リリースまでに追加するメインの機能は以下になっております
- 管理者機能
- バックエンドのテスト

お忙しいところ恐れ入りますが、
ご確認よろしくお願いいたします🙇🏼‍♀️

**Comment by kenchasonakai** [comment]
> ②の代替案として、チームタスク機能を拡張させて、例えばタスクが登録された際にLINE通知を飛ばす、タスクに関してコメントができるなどすれば、上記にあげた目的をより実現しやすいのかなと考えていますがいかがでしょうか。

良いと思います！
